---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: barbican-exporter-monitor
  namespace: openstack
  labels:
    prometheus: kube-prometheus-stack-prometheus
spec:
  selector:
    matchLabels:
      app: barbican-exporter
  endpoints:
    - port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - openstack
