---
apiVersion: v1
kind: Service
metadata:
  name: barbican-exporter
  namespace: openstack
  labels:
    app: barbican-exporter
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: barbican-exporter
  type: ClusterIP
